### ISSUE TITLE
Browser to view data

### ISSUE THREAD

**Issue by aznj** [pilgr/Paper#144]
How can I view data that was saved? Is there any application that able to do this?

**Comment by pilgr** [comment]
@aznj No, you can't. This is not available by design. Paper has been designed from the ground up as a scheme-less data storage meaning you and only you (who saved the data) can read them back properly. Paper serialize classes data into binary and requires the exact same classes to read data back. This helps Paper to be very fast and support seamless migration to the updated class structures. But as a downside – no data browser.

To look at the data (if you can read them programmatically) I'd sugggest to save it to JSON file once read is done. This is not a part of Paper and should be implemented on the client side if needed.
