### ISSUE TITLE
Add versioning/migration API

### ISSUE THREAD

**Issue by ZakTaccardi** [pilgr/Paper#23]
An api for migrating data across different versions would be nice

**Comment by pilgr** [comment]
Paper has been designed around the idea that migration is not needed and should be done automatically. Have you met the case when the real migration is still needed?

**Comment by ZakTaccardi** [comment]
I'm using it as my sole database, which is why I would like the migration.

I'm not asking for migrating a class between versions, but for the migrated the serialized data persisted in a `Paper.book()` between versions.

**Comment by pilgr** [comment]
Yep, makes sense.

**Comment by Dosssik** [comment]
@pilgr Hi there!
Is it possible to handle following case:
1) We saved some pojo `Item` in Paper in usual way - `Paper.book().write("TABLE_NAME_KEY", item) `
2) After some time we decide to move our item from one package to another. E.g. that was `com.test.app.firstpackage.Item` and become `com.test.app.secondpackage.Item`
3) If we update our app with new package structure and trying to get saved item from Paper - we getting error:
`Caused by: io.paperdb.PaperDbException: Couldn't read/deserialize file /data/user/0/com.test.app/files/io.paperdb/TABLE_NAME_KEY.pt"`

Is there any way to hadle that issue? 
Thanks in advance

**Comment by pilgr** [comment]
@Dosssik you have to make a migration manually: having both classes available in the next version and manually read using the old class to migrate data to the new one. It's like changing the table name in SQL database – you need a migration script.
